name: CI

on: [push, pull_request]

jobs:
  build_xbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
          chmod +x dependencies/linux/superfreq
          pip install gitpython
          pip install mido
      - name: Remove PS3 files
        run: |
          find . -name "*.*_ps3" -type f -delete
      - name: Build ARK
        run: |
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 4 -f
      - name: Remove Excess files
        run: |
          find . -name "*.txt" -type f -delete
          find . -name "*.zbm" -type f -delete
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB1DX-Xbox
          path: _build/xbox

  build_ps3:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set env
        run: |
          pip install gitpython
          pip install mido
          pip install requests
      - name: fetch TrueAncestor PKG Repacker
        run: |
          python dependencies/dev_scripts/download_ta_pkg_repacker.py
      - name: Remove Xbox files
        run: |
          Get-ChildItem _ark/ -recurse -include *.*_xbox | remove-item
      - name: Build ARK
        run: |
          dependencies/windows/arkhelper.exe dir2ark _ark _build/ps3/USRDIR/gen -n "patch_ps3" -e -v 4 -f
      - name: Build PKG
        run: |
          $sha_short="$(git rev-parse --short HEAD)".ToUpper()
          $content="UP0006-BLUS30050_00-RB1DXNITE"
          $packageversion="1.07"
          dependencies/ta_pkg_repacker_tools/make_package_npdrm_retail.exe --k-licensee 0x00000000000000000000000000000000 --drm-type Local --package-version $packageversion --content-type GameData --content-id ($content + $sha_short) dependencies/ta_pkg_repacker_tools/package.conf _build/ps3

      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: RB1DX-PS3
          path: '*.pkg'
